# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XtHl6Tr5DgrKVxIyDzIUnZwY1fWhqLLT
"""

#Python program to print all odd numbers in a list
print("Enter 10 numbers in a list")
number = []
for x in range(10):
  a = int(input("Enter any number: "))
  number.append(a)
odd_number = []
for x in number:
  if x % 2 == 1:
    odd_number.append(x)
print(odd_number)

#Python program to find the sum of list elements
print("Enter 10 numbers in a list")
numbers = []
for x in range(10):
  a = int(input("Enter any number: "))
  numbers.append(a)
sum = 0
for x in numbers:
  sum += x
print (sum)

#Python program to reverse a list in two ways
print("Enter 10 values in a list")
List = []
for x in range(10):
  a = input("Enter any number: ")
  List.append(a)
print ("Original list")
print (List)
print("Reversed List (1st Method)")
List.reverse()
ListCopy = List
print(List)
print("Reversed List in original form (2nd Method)")
print(ListCopy[-1::-1])

#Python program to find top two maximimum numbers in a list
print("Enter 10 numbers in a list")
number = []
for x in range(10):
  a = int(input("Enter any number: "))
  number.append(a)
max = 0
for x in range(9):
  if max < number[x]:
    max = number[x]
number.remove(max)
print("The maximum number in the list is: " , max)
sec_max = 0
for x in range(9):
  if sec_max < number[x]:
    sec_max = number[x]
print("The second highest number in the list is: " , sec_max)

#Python program to find second highest number in a list
print("Enter 10 numbers in a list")
number = []
for x in range(10):
  a = int(input("Enter any number: "))
  number.append(a)
max = 0
for x in range(9):
  if max < number[x]:
    max = number[x]
number.remove(max)
sec_max = 0
for x in range(9):
  if sec_max < number[x]:
    sec_max = number[x]
print("The second highest number in the list is: " , sec_max)

#Python program to sort characters in descending order
print("Enter 10 characters in a list")
character = []
for x in range(10):
  a = input("Enter any character: ")
  character.append(a)
print(sorted(character))

#Python program to remove repeated characters from a string.
string = input("Enter a string: ")
k = 0
for i in string:
  
  for j in string:
    if i == j:
      string.replace(j,"")
  k += 1
  print(string[k] , end = "")

#Python program to check if a given character is a vowel or consonant.
char = input("Enter any character: ")
if char == 'a' or char == 'e' or char == 'i' or char == 'o' or char == 'u':
  print(char , "is a vowel")
else:
  print(char , "is a consonent")

#Python Program to calculate factorial.
num = int(input("Enter any integer to find the factorial: "))
fact = 1
for x in range(num , 1 , -1):
  fact *= x
print(fact)

#Python Program to merge two lists.
print("Enter 10 values in a list 1")
List1 = []
List2 = []
for x in range(4):
  a = input("Enter any number: ")
  List1.append(a)
for x in range(4):
  a = input("Enter any number: ")
  List2.append(a)
Combined = List1 + List2
print(Combined)

